Release 1.0.0-rc6
DataDog/dd-sdk-reactnative pull request #179
Opened 2022-05-11 09:33 UTC by louiszawadzki

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)
- [ ] If this PR is auto-generated, please make sure also to manually update the code related to the change

2022-05-11 12:41 UTC, 0xnm approved these changes

2022-05-11 18:41 UTC, alai97 approved these changes

2022-05-13 15:30 UTC, louiszawadzki commented
@alai97 what has changed since your review:
- we introduced the `resourceTracingSamplingRate` configuration key to sample RUM to APM traces
- we renamed the `sampleRate` configuration key to `sessionSampleRate` to avoid confusion with the new key

2022-05-17 15:41 UTC, alai97 requested changes

2022-05-17 15:41 UTC, alai97 commented on packages/core/README.md
> + that Build Tools version 31+, Android Gradle Plugin 7+ and Gradle 7+ should be used. You can modify the versions used by changing the values in the `buildscript.ext` block of your app's top-level `b
```suggestion
Versions `1.0.0-rc5` and higher require you to have `compileSdkVersion = 31` in the Android application setup, which implies that you should use Build Tools version 31, Android Gradle Plugin version 7, and Gradle version 7 or higher. To modify the versions, change the values in the `buildscript.ext` block of your application's top-level `build.gradle` file. Datadog recommends using React Native version 0.67 or higher.
```

2022-05-17 15:41 UTC, alai97 commented on README.md
> + that Build Tools version 31+, Android Gradle Plugin 7+ and Gradle 7+ should be used. You can modify the versions used by changing the values in the `buildscript.ext` block of your app's top-level `b
```suggestion
Versions `1.0.0-rc5` and higher require you to have `compileSdkVersion = 31` in the Android application setup, which implies that you should use Build Tools version 31, Android Gradle Plugin version 7, and Gradle version 7 or higher. To modify the versions, change the values in the `buildscript.ext` block of your application's top-level `build.gradle` file. Datadog recommends using React Native version 0.67 or higher.
```

2022-05-18 06:54 UTC, xgouchet approved these changes

2022-05-18 07:38 UTC, 0xnm approved these changes

2022-05-18 11:49 UTC, merged