Update to version 0.3
DataDog/dd-sdk-reactnative pull request #36
Opened 2021-04-07 06:43 UTC by xgouchet

This PR has been created automatically by the CI

2021-04-07 07:08 UTC, mariusc83 approved these changes

2021-04-07 07:19 UTC, 0xnm requested changes

2021-04-07 07:19 UTC, 0xnm commented on src/index.tsx
> -import { DdSdkConfiguration } from './types';
I didn't know that this file is also generated. This diff is wrong then and we need to update generator.

2021-04-13 10:07 UTC, 0xnm requested changes

2021-04-13 10:07 UTC, 0xnm commented on src/types.tsx
> -    readonly additionalConfig: object = {}
we need to either put it back or modify this line https://github.com/DataDog/dd-sdk-reactnative/blob/abfd9a7ecb2b231f5e8d1c657219caa302702cad/src/DdSdkReactNative.tsx#L35

2021-04-13 10:08 UTC, 0xnm approved these changes

2021-04-14 16:23 UTC, jtappa approved these changes
👍🏻  from docs

2021-04-19 11:57 UTC, 0xnm approved these changes

2021-04-19 12:07 UTC, merged