Update documentation for XCode build phase
DataDog/dd-sdk-reactnative pull request #409
Opened 2023-02-16 13:50 UTC by louiszawadzki

### What does this PR do?

Update documentation on how to execute `datadog-ci` from XCode.

### Review checklist (to be filled by reviewers)

- [x] Feature or bugfix MUST have appropriate tests
- [x] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [x] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)
- [x] If this PR is auto-generated, please make sure also to manually update the code related to the change

2023-02-16 15:18 UTC, fuzzybinary approved these changes

2023-02-16 19:09 UTC, cswatt requested changes

2023-02-16 19:09 UTC, cswatt commented on docs/crash_reporting.md
> +It runs a command that takes care of uploading the source maps with all the correct parameters. For more information, see the [datadog-ci documentation][12].
```suggestion
This script runs a command that takes care of uploading the source maps with all the correct parameters. For more information, see the [datadog-ci documentation][12].
```

2023-02-16 19:09 UTC, cswatt commented on docs/crash_reporting.md
> +It runs a command that takes care of uploading the source maps with all the correct parameters. For more information, see the [datadog-ci documentation][12].
```suggestion
This script runs a command that takes care of uploading the source maps with all the correct parameters. For more information, see the [datadog-ci documentation][12].
```

2023-02-20 08:51 UTC, xgouchet approved these changes

2023-02-22 19:36 UTC, buraizu approved these changes

2023-02-23 09:08 UTC, merged