Enable custom service name for Android sourcemaps
DataDog/dd-sdk-reactnative pull request #421
Opened 2023-03-06 17:29 UTC by louiszawadzki

### What does this PR do?

Enable custom service name for Android sourcemaps.

### Motivation

Enable customers using a custom service name to upload their sourcemaps automatically on Android.
The solution does not require to add new files, as this is not so common.

### Additional Notes

If users need to specify different service name per environment, they can use environment variables.

### Review checklist (to be filled by reviewers)

- [x] Feature or bugfix MUST have appropriate tests
- [x] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [x] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)
- [x] If this PR is auto-generated, please make sure also to manually update the code related to the change

2023-03-06 18:48 UTC, fuzzybinary approved these changes

2023-03-06 18:48 UTC, fuzzybinary commented on docs/crash_reporting.md
> +Available options for the `datadog-ci react-native xcode` command are available on the [command documentation page].
Shole "command documentation page" have a footnote link?

2023-03-06 23:14 UTC, rtrieu requested changes
Missing link

2023-03-06 23:14 UTC, rtrieu commented on docs/crash_reporting.md
> +Available options for the `datadog-ci react-native xcode` command are available on the [command documentation page].
+1

2023-03-07 07:24 UTC, 0xnm approved these changes

2023-03-07 07:24 UTC, 0xnm commented on packages/core/datadog-sourcemaps.gradle
> +    if (project.hasProperty("datadog")) {
won't something like this work? anyway, this doesn't really change anything.

```suggestion
    if (project.datadog != null && project.datadog.serviceName != null) {
```

2023-03-08 17:20 UTC, rtrieu requested changes
Minor update - link formatting.

2023-03-08 17:20 UTC, rtrieu commented on docs/crash_reporting.md
> +Available options for the `datadog-ci react-native xcode` command are available on the [command documentation page](12).
```suggestion
Available options for the `datadog-ci react-native xcode` command are available on the [command documentation page][12].
```

2023-03-08 22:11 UTC, rtrieu approved these changes
Looks good!

2023-03-09 10:23 UTC, merged