Update mockito-kotlin version
DataDog/dd-sdk-reactnative pull request #564
Opened 2023-12-06 13:12 UTC by jonathanmos

### What does this PR do?
Update mockito kotlin version

### Motivation
Needed to enable mocking of React views so that we can test them in SR unit tests

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)
- [ ] If this PR is auto-generated, please make sure also to manually update the code related to the change

2023-12-06 13:33 UTC, 0xnm approved these changes, later dismissed

2023-12-06 13:33 UTC, xgouchet submitted a review, later dismissed

2023-12-06 13:39 UTC, louiszawadzki requested changes
Asked a question on why we need to set the `jvmTarget`.
If we do use it, we need to only add it for AGP versions below 8.0 to retain compatibility.

Also it would be nice to migrate the core SDK at the same time to unify tooling, do you know what the effort would be to do so?

2023-12-06 13:39 UTC, louiszawadzki commented on packages/react-native-session-replay/android/build.gradle
> +}
Why do we need to set the `jvmTarget` here and why to version 11?
The Android SDK is on version 17: https://github.com/DataDog/dd-sdk-android/blob/develop/buildSrc/build.gradle.kts#L83

A few points if we need this:
- we need to only set the jvmTarget version if AGP version is below 8.0: https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1677632448
- since mockito is only used for tests, can we only set the `jvmTarget` when running tests to avoid risks of breaking builds for customers?
- can we also bring this change (and the mockito upgrade) to the core SDK as well?

2023-12-06 13:46 UTC, 0xnm commented on packages/react-native-session-replay/android/build.gradle
> +}
@louiszawadzki Android SDK is [producing JVM 11 bytecode](https://github.com/DataDog/dd-sdk-android/blob/f38f6beabc2aef5355ae68f89efa277aa359676b/dd-sdk-android-core/build.gradle.kts#L146) for artifacts published. JVM 17 bytecode you are referencing will be effective only for non-customer facing code.

2023-12-06 14:44 UTC, jonathanmos commented on packages/react-native-session-replay/android/build.gradle
> +}
Upgrading the mockito-kotlin version causes argumentCaptor to throw
```Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option```
I'll put this inside a block that only runs for tests.

I'm now working on doing the same changes for the core 👍

2023-12-07 07:57 UTC, xgouchet approved these changes

2023-12-07 10:11 UTC, louiszawadzki approved these changes

2023-12-07 15:22 UTC, merged