RUMM-1400 Handle undefined nested route in React Navigation instrumentation
DataDog/dd-sdk-reactnative pull request #57
Opened 2021-06-02 14:06 UTC by xgouchet

### What does this PR do?

Handles a case in which sometimes the `nestedRoute` variable becomes undefined.

2021-06-02 14:22 UTC, 0xnm approved these changes

2021-06-02 15:04 UTC, mariusc83 requested changes

2021-06-02 15:04 UTC, mariusc83 commented on src/rum/instrumentation/DdRumReactNavigationTracking.tsx
> +                        // RUMM-1400 in some cases the route seem to be undefined
You are not logging this here but you do in the upper level. Maybe you could extract this check in a `isValidRoute` method and reuse it in both places.

2021-06-03 16:55 UTC, mariusc83 approved these changes

2021-06-04 06:49 UTC, merged