RUMM-1518 Add Readme for each subpackage
DataDog/dd-sdk-reactnative pull request #92
Opened 2021-08-02 14:33 UTC by xgouchet

### What does this PR do?

Add the appropriate README for each package

2021-08-02 14:41 UTC, 0xnm requested changes

2021-08-02 14:41 UTC, 0xnm commented on packages/react-navigation/README.md
> +npm install @datadog/mobile-react-native-navigation
```suggestion
npm install @datadog/mobile-react-navigation
```

2021-08-02 14:41 UTC, 0xnm commented on packages/react-navigation/README.md
> +yarn add @datadog/mobile-react-native-navigation
```suggestion
yarn add @datadog/mobile-react-navigation
```

2021-08-02 14:41 UTC, 0xnm commented on packages/core/README.md
> +Because React Native offers a wide range of libraries to create screen navigation, by default only manual View tracking is supported. You can manually start and stop a View using the following `start
maybe we should do a link to the support packages here as well? wdyt?

2021-08-02 14:41 UTC, 0xnm commented on packages/react-navigation/README.md
> +```js
this code block should be updated for `react-navigation` example.

2021-08-02 16:54 UTC, 0xnm approved these changes

2021-08-03 20:03 UTC, cswatt approved these changes

2021-08-04 07:58 UTC, merged